### PR TITLE
HTCONDOR-1381 default TRUST_DOMAIN to UID_DOMAIN

### PR DESCRIPTION
**Pull request by johnkn**
<Insert PR description here, and leave checklist below for code review.>

# HTCondor Pull Request Checklist for internal reviewers

- [x] Verify that (GitHub thinks) the merge is clean. If it isn't, and you're confident you can resolve the conflicts, do so. Otherwise, send it back to the original developer.
- [x] Verify that the related Jira ticket exists and has a target version number and that it is correct.
- [x] Verify that the Jira ticket is in review status and is assigned to the reviewer.
- [x] Verify that the Jira ticket (HTCONDOR-xxx) is mentioned at the beginning of the title. Edit it, if not
- [x] Verify that the branch destination of the PR matches the target version of the ticket
- [x] Check for correctness of change
- [x] Check for regression test(s) of new features and bugfixes (if the feature doesn't require root)
- [x] Check for documentation, if needed
- [x] Check for version history, if needed
- [x] Check BaTLab dashboard for successful build (https://batlab.chtc.wisc.edu/results/workspace.php) and test for either the PR or a workspace build by the developer that has the Jira ticket as a comment.
- [x] Check that each commit message references the Jira ticket (HTCONDOR-xxx)

## After the above
- Hit the merge button if the pull request is approved and it is not a security patch (security changes require 2 additional reviews)
- If the pull request is approved, take the ticket out of review state
- Assign JIRA Ticket back to the developer

### CODE REVIEW

**Comment by bbockelm** [comment]
What are the compatibility issues here?  Won't this cause a "flag day" which invalidates almost all of the existing tokens and require many things to be updated in lockstep?

**Review by Todd-L-Miller — COMMENTED** [review]
The new default is clearly better, but it also clearly needs to be written up in the "upgrading to 10.0" section (and possibly therefore in the release notes), since it could break the pool if people upgrade without checking to see if `$(COLLECTOR_HOST)` is sensible.  The write-up should strongly urge admins who are upgrading and therefore need to pay attention to this to set `TRUST_DOMAIN` to a string constant (e..g, the old value of `COLLECTOR_HOST`), unless they want their pool to break if the location of their collector ever changes.

**Comment by JaimeFrey** [comment]
Additional language in the manual will happen in a separate PR.

**Review by JaimeFrey — APPROVED** [review]
Looks good.

**Pull request merged**
