### PR TITLE
HTCONDOR-2172: Add Fedora 39

### PR DESCRIPTION
**Pull request by timtheisen**
<Insert PR description here, and leave checklist below for code review.>

# HTCondor Pull Request Checklist for internal reviewers

- [ ] Verify that (GitHub thinks) the merge is clean. If it isn't, and you're confident you can resolve the conflicts, do so. Otherwise, send it back to the original developer.
- [ ] Verify that the related Jira ticket exists and has a target version number and that it is correct.
- [ ] Verify that the Jira ticket is in review status and is assigned to the reviewer.
- [ ] Verify that the Jira ticket (HTCONDOR-xxx) is mentioned at the beginning of the title. Edit it, if not
- [ ] Verify that the branch destination of the PR matches the target version of the ticket
- [ ] Check for correctness of change
- [ ] Check for regression test(s) of new features and bugfixes (if the feature doesn't require root)
- [ ] Check for documentation, if needed  (documentation [build logs](https://readthedocs.org/projects/htcondor/builds/))
- [ ] Check for version history, if needed
- [ ] Check BaTLab dashboard for successful build (https://batlab.chtc.wisc.edu/results/workspace.php) and test for either the PR or a workspace build by the developer that has the Jira ticket as a comment.
- [ ] Check that each commit message references the Jira ticket (HTCONDOR-xxx)

## After the above
- Hit the merge button if the pull request is approved and it is not a security patch (security changes require 2 additional reviews)
- If the pull request is approved, take the ticket out of review state
- Assign JIRA Ticket back to the developer

### CODE REVIEW

**Review by GregThain — CHANGES_REQUESTED** [review]
Can we remove Fedora 38 in this same commit?  We're building a lot of platforms on every commit now.

**Review by GregThain — CHANGES_REQUESTED** [review]
Also, do we know where these warnings are coming from:

```
mangling shebang in /usr/libexec/blahp/lsf_resume.sh from /bin/bash to #!/usr/bin/bash
mangling shebang in /usr/libexec/blahp/kubernetes_cancel.sh from /bin/bash to #!/usr/bin/bash
+ /usr/lib/rpm/brp-remove-la-files
+ env -u SOURCE_DATE_EPOCH /usr/lib/rpm/redhat/brp-python-bytecompile '' 1 0 -j8
Bytecompiling .py files below /var/lib/condor/execute/slot1/dir_3368958/userdir/build-7UoK6f/BUILDROOT/condor-23.4.0-0.700263.fc39.x86_64/usr/lib64/python3.12 using python3.12
Not clamping source mtimes, $SOURCE_DATE_EPOCH not set
/usr/lib64/python3.12/site-packages/classad/__init__.py:28: SyntaxWarning: invalid escape sequence '\l'
  """
/usr/lib64/python3.12/site-packages/classad/__init__.py:28: SyntaxWarning: invalid escape sequence '\l'
  """
/usr/lib64/python3.12/site-packages/htcondor/__init__.py:53: SyntaxWarning: invalid escape sequence '\l'
  """
/usr/lib64/python3.12/site-packages/htcondor/__init__.py:79: SyntaxWarning: invalid escape sequence '\D'
  __version__ = _re.match("^\D*(\d+\.\d+\.\d+)\D", htcondor.version()).group(1)
/usr/lib64/python3.12/site-packages/htcondor/__init__.py:53: SyntaxWarning: invalid escape sequence '\l'
  """
/usr/lib64/python3.12/site-packages/htcondor/__init__.py:79: SyntaxWarning: invalid escape sequence '\D'
  __version__ = _re.match("^\D*(\d+\.\d+\.\d+)\D", htcondor.version()).group(1)
/usr/lib64/python3.12/site-packages/htcondor2/_schedd.py:53: SyntaxWarning: invalid escape sequence '\d'
/usr/lib64/python3.12/site-packages/htcondor2/_schedd.py:53: SyntaxWarning: invalid escape sequence '\d'
/usr/lib64/python3.12/site-packages/htcondor_cli/job_set.py:266: SyntaxWarning: invalid escape sequence '\$'
  return submit_obj
/usr/lib64/python3.12/site-packages/htcondor_cli/job_set.py:266: SyntaxWarning: invalid escape sequence '\)'
  return submit_obj
/usr/lib64/python3.12/site-packages/htcondor_cli/job_set.py:266: SyntaxWarning: invalid escape sequence '\$'
  return submit_obj
/usr/lib64/python3.12/site-packages/htcondor_cli/job_set.py:266: SyntaxWarning: invalid escape sequence '\)'
  return submit_obj
Bytecompiling .py files below /var/lib/condor/execute/slot1/dir_3368958/userdir/build-7UoK6f/BUILDROOT/condor-23.4.0-0.700263.fc39.x86_64/usr/lib/debug/usr/lib64/python3.12 using python3.12
```

**Comment by timtheisen** [comment]
> Also, do we know where these warnings are coming from:
> 
> ```
> mangling shebang in /usr/libexec/blahp/lsf_resume.sh from /bin/bash to #!/usr/bin/bash
> mangling shebang in /usr/libexec/blahp/kubernetes_cancel.sh from /bin/bash to #!/usr/bin/bash
> + /usr/lib/rpm/brp-remove-la-files
> + env -u SOURCE_DATE_EPOCH /usr/lib/rpm/redhat/brp-python-bytecompile '' 1 0 -j8
> Bytecompiling .py files below /var/lib/condor/execute/slot1/dir_3368958/userdir/build-7UoK6f/BUILDROOT/condor-23.4.0-0.700263.fc39.x86_64/usr/lib64/python3.12 using python3.12
> Not clamping source mtimes, $SOURCE_DATE_EPOCH not set
> /usr/lib64/python3.12/site-packages/classad/__init__.py:28: SyntaxWarning: invalid escape sequence '\l'
>   """
> /usr/lib64/python3.12/site-packages/classad/__init__.py:28: SyntaxWarning: invalid escape sequence '\l'
>   """
> /usr/lib64/python3.12/site-packages/htcondor/__init__.py:53: SyntaxWarning: invalid escape sequence '\l'
>   """
> /usr/lib64/python3.12/site-packages/htcondor/__init__.py:79: SyntaxWarning: invalid escape sequence '\D'
>   __version__ = _re.match("^\D*(\d+\.\d+\.\d+)\D", htcondor.version()).group(1)
> /usr/lib64/python3.12/site-packages/htcondor/__init__.py:53: SyntaxWarning: invalid escape sequence '\l'
>   """
> /usr/lib64/python3.12/site-packages/htcondor/__init__.py:79: SyntaxWarning: invalid escape sequence '\D'
>   __version__ = _re.match("^\D*(\d+\.\d+\.\d+)\D", htcondor.version()).group(1)
> /usr/lib64/python3.12/site-packages/htcondor2/_schedd.py:53: SyntaxWarning: invalid escape sequence '\d'
> /usr/lib64/python3.12/site-packages/htcondor2/_schedd.py:53: SyntaxWarning: invalid escape sequence '\d'
> /usr/lib64/python3.12/site-packages/htcondor_cli/job_set.py:266: SyntaxWarning: invalid escape sequence '\$'
>   return submit_obj
> /usr/lib64/python3.12/site-packages/htcondor_cli/job_set.py:266: SyntaxWarning: invalid escape sequence '\)'
>   return submit_obj
> /usr/lib64/python3.12/site-packages/htcondor_cli/job_set.py:266: SyntaxWarning: invalid escape sequence '\$'
>   return submit_obj
> /usr/lib64/python3.12/site-packages/htcondor_cli/job_set.py:266: SyntaxWarning: invalid escape sequence '\)'
>   return submit_obj
> Bytecompiling .py files below /var/lib/condor/execute/slot1/dir_3368958/userdir/build-7UoK6f/BUILDROOT/condor-23.4.0-0.700263.fc39.x86_64/usr/lib/debug/usr/lib64/python3.12 using python3.12
> ```

New Python (3.12) new warnings.

**Comment by timtheisen** [comment]
> Can we remove Fedora 38 in this same commit? We're building a lot of platforms on every commit now.

As long as I push this downstream to Fedora 38, I'd like to keep building it. Or perhaps, we could drop it here and just update Fedora 38 with LTS versions.

**Comment by timtheisen** [comment]
In any case, I'd like to merge it to ensure that the Python fixes for HTCONDOR-2122 are complete.

**Comment by GregThain** [comment]
OK, I'll merge this, but I'd really like to take Fedora 38 out of our CI builds, as that makes 19, and it's a lot to wait for.

**Review by GregThain — APPROVED** [review]
LGTM, but let's quickly remove F38 from the CI build/tests.

**Pull request merged**
