### PR TITLE
parameter passing to BOINC

### PR DESCRIPTION
**Pull request by nikolasgianna**
This pull request is to make it possible to set the following parameters:

rsc_fpops_est, rsc_fpops_bound, rsc_memory_bound, rsc_disk_bound, delay_bound, app_version_num

when submitting to BOINC through Condor.

See: https://github.com/BOINC/boinc/pull/2377

### CODE REVIEW

**Comment by timtheisen** [comment]
Sorry this took so long. It is being review for inclusion in our next development release (8.7.10)
Here is the corresponding ticket.
https://htcondor-wiki.cs.wisc.edu/index.cgi/tktview?tn=6760

**Comment by timtheisen** [comment]
Could you please complete a contributor's license agreement and send it to htcondor-admin@cs.wisc.edu
http://research.cs.wisc.edu/htcondor/licenses/CLA-PUBLIC.pdf

**Comment by timtheisen** [comment]
It is likely that you are associated with CERN. If so, CERN has signed the License Agreement for the whole organization. Just email tim@cs.wisc.edu to let me know.

**Comment by nikolasgianna** [comment]
Hello. I was associated with CERN when I wrote this pull request but I am
no longer associated with it. Should I go ahead and sign the license
agreement or is it not necessary?

**Pull request merged**
