### PR TITLE
HTCONDOR-2466 local-ips-alias

### PR DESCRIPTION
**Pull request by JaimeFrey**
<Insert PR description here, and leave checklist below for code review.>

# HTCondor Pull Request Checklist for internal reviewers

- [x] Verify that (GitHub thinks) the merge is clean. If it isn't, and you're confident you can resolve the conflicts, do so. Otherwise, send it back to the original developer.
- [x] Verify that the related Jira ticket exists and has a target version number and that it is correct.
- [x] Verify that the Jira ticket is in review status and is assigned to the reviewer.
- [x] Verify that the Jira ticket (HTCONDOR-xxx) is mentioned at the beginning of the title. Edit it, if not
- [x] Verify that the branch destination of the PR matches the target version of the ticket
- [x] Check for correctness of change
- [ ] Check for regression test(s) of new features and bugfixes (if the feature doesn't require root)
- [x] Check for documentation, if needed  (documentation [build logs](https://readthedocs.org/projects/htcondor/builds/))
- [x] Check for version history, if needed
- [ ] Check BaTLab dashboard for successful build (https://batlab.chtc.wisc.edu/results/workspace.php) and test for either the PR or a workspace build by the developer that has the Jira ticket as a comment.
- [x] Check that each commit message references the Jira ticket (HTCONDOR-xxx)

## After the above
- Hit the merge button if the pull request is approved and it is not a security patch (security changes require 2 additional reviews)
- If the pull request is approved, take the ticket out of review state
- Assign JIRA Ticket back to the developer

### CODE REVIEW

**Review by Todd-L-Miller — COMMENTED** [review]
The difference between "are usable on the local machine" and "are on the local machine" is probably both subtle and important; the documentation and the release note should probably use the same language.

**Comment by JaimeFrey** [comment]
Yeah, I was waffling on that. The main points we need to convey are 1) useable addresses and 2) in the current environment (i.e. not virtual addresses inside a container if you're on the physical host and vice versa).

**Review by Todd-L-Miller — APPROVED** [review]
Code looks good; nice and simple.  Approved pending BaTLab results.

It might be hard to write a test for the negative (nonlocal) cases, but it shouldn't be hard to the positive cases.  I'll leave it to you if it's worth writing half a test.

**Comment by Todd-L-Miller** [comment]
> Yeah, I was waffling on that. The main points we need to convey are 1) usable addresses and 2) in the current environment (i.e. not virtual addresses inside a container if you're on the physical host and vice versa).

I think "are usable on the local machine" is fine phrasing, it just should probably be used in the release note, as well.  We can add a parenthetical remark (or footnote) defining usable as "bind()able" as necessary.

**Pull request merged**
