### PR TITLE
(HTCONDOR-2153)  issue_credentials()

### PR DESCRIPTION
**Pull request by Todd-L-Miller**
Hook `condor_submit`'s credential handling into the Python bindings.

# HTCondor Pull Request Checklist for internal reviewers

- [x] Verify that (GitHub thinks) the merge is clean. If it isn't, and you're confident you can resolve the conflicts, do so. Otherwise, send it back to the original developer.
- [x] Verify that the related Jira ticket exists and has a target version number and that it is correct.
- [ ] Verify that the Jira ticket is in review status and is assigned to the reviewer.
- [x] Verify that the Jira ticket (HTCONDOR-xxx) is mentioned at the beginning of the title. Edit it, if not
- [x] Verify that the branch destination of the PR matches the target version of the ticket
- [x] Check for correctness of change
- [x] Check for regression test(s) of new features and bugfixes (if the feature doesn't require root)
- [ ] Check for documentation, if needed  (documentation [build logs](https://readthedocs.org/projects/htcondor/builds/))
- [ ] Check for version history, if needed
- [x] Check BaTLab dashboard for successful build (https://batlab.chtc.wisc.edu/results/workspace.php) and test for either the PR or a workspace build by the developer that has the Jira ticket as a comment.
- [x] Check that each commit message references the Jira ticket (HTCONDOR-xxx)

## After the above
- Hit the merge button if the pull request is approved and it is not a security patch (security changes require 2 additional reviews)
- If the pull request is approved, take the ticket out of review state
- Assign JIRA Ticket back to the developer

### CODE REVIEW

**Comment by Todd-L-Miller** [comment]
JaimeF OK'd this going in with only one of the methods tested, based on the way the code currently works.

**Comment by Todd-L-Miller** [comment]
As is traditional, no release note for the version 2 bindings because they don't officially exist yet.

**Comment by Todd-L-Miller** [comment]
This ended up being more code than I expected, so while it probably deserves its own ticket, it's instead part of the version 2 bindings parent ticket.

**Comment by ColeBollig** [comment]
@Todd-L-Miller New test is failing

**Comment by Todd-L-Miller** [comment]
The test depends on the Python module `scitokens`, which I'd assumed would be available (as a runtime dependency of a component of the HTCSS).  I've asked TimT to add it to the containers.

**Comment by Todd-L-Miller** [comment]
The test failures on Ubuntu 20 are caused by weird crypto nonsense on that platform:
```
05/17/24 17:58:17.162 (D_ALWAYS) WARNING: LOCAL_CREDMON_PRIVATE_KEY must use elipitcal curve cryptograph algorithm
05/17/24 17:58:17.162 (D_ALWAYS) WARNING: `scitokens-admin-create-key --pem-private` should be used with `--ec` option
05/17/24 17:58:17.162 (D_ALWAYS) WARNING: Errors are likely to occur when attempting to serialize SciTokens
```
...
```
05/17/24 19:02:53.351 (D_ERROR) Failure when attempting to serialize a SciToken, likely due to algorithm mismatch
```
related to using the auto-generated host cert.  For now, I'll just disable the test on those two platforms.

**Review by ColeBollig — APPROVED** [review]
LGTM

**Pull request merged**
