### PR TITLE
HTCONDOR-1288 Refactor condor_adstash for future development

### PR DESCRIPTION
**Pull request by jasoncpatton**
https://opensciencegrid.atlassian.net/browse/HTCONDOR-1288

This refactor decouples condor_adstash from being dependent upon condor_history
and Elasticsearch. This will speed up future development of condor_adstash
when adding new ClassAd sources and stash targets. Additionally, some small
annoyances were fixed along the way:

1. “updated mappings” JSON file now ends up in $(LOG) by default
2. Checkpoint files are written atomically.
3. Nested attributes are now properly defined.

# HTCondor Pull Request Checklist for internal reviewers

- [ ] Verify that (GitHub thinks) the merge is clean. If it isn't, and you're confident you can resolve the conflicts, do so. Otherwise, send it back to the original developer.
- [ ] Verify that the related Jira ticket exists and has a target version number and that it is correct.
- [ ] Verify that the Jira ticket is in review status and is assigned to the reviewer.
- [ ] Verify that the Jira ticket (HTCONDOR-xxx) is mentioned at the beginning of the title. Edit it, if not
- [ ] Verify that the branch destination of the PR matches the target version of the ticket
- [ ] Check for correctness of change
- [ ] Check for regression test(s) of new features and bugfixes (if the feature doesn't require root)
- [ ] Check for documentation, if needed
- [ ] Check for version history, if needed
- [ ] Check BaTLab dashboard for successful build (https://batlab.chtc.wisc.edu/results/workspace.php) and test for either the PR or a workspace build by the developer that has the Jira ticket as a comment.
- [ ] Check that commit message references the Jira ticket (HTCONDOR-xxx)

## After the above
- Hit the merge button if the pull request is approved and it is not a security patch (security changes require 2 additional reviews)
- If the pull request is approved, take the ticket out of review state
- Assign JIRA Ticket back to the developer

### CODE REVIEW

**Comment by jasoncpatton** [comment]
@iross Apparently I can't add you as a reviewer on this... argh. If everything looks good per @iross, @timtheisen can you facilitate the merge?

**Comment by jasoncpatton** [comment]
@iross also, I'm working on updating docs (man-page needs some love) before setting this to active.

**Comment by jasoncpatton** [comment]
@iross I have broken the RHEL builds... investigating.

**Comment by jasoncpatton** [comment]
I expect https://github.com/htcondor/htcondor/pull/820/commits/d455c2bfd85b374469a299333ac5d73f799e8349 to fix the build... Build ID 603718 should be green (except for AlmaLinux) 🤞

**Review by iross — APPROVED** [review]
From a high-level view, this all looks good to me. Nothing jumps out as a show-stopper from a structural or approach-based point of view.

**Pull request merged**
