### PR TITLE
HTCONDOR-283 HTCONDOR-287 HTCONDOR-1054 HTCONDOR-1057 replay and key exchange improvements

### PR DESCRIPTION
**Pull request by JaimeFrey**
Add replay protection and improve key exchange

# HTCondor Pull Request Checklist for internal reviewers

- [x] Verify that (GitHub thinks) the merge is clean. If it isn't, and you're confident you can resolve the conflicts, do so. Otherwise, send it back to the original developer.
- [x] Verify that the related Jira ticket exists and has a target version number and that it is correct.
- [x] Verify that the Jira ticket is in review status and is assigned to the reviewer.
- [x] Verify that the Jira ticket (HTCONDOR-xxx) is mentioned at the beginning of the title. Edit it, if not
- [x] Verify that the branch destination of the PR matches the target version of the ticket
- [x] Check for correctness of change
- [x] Check for regression test(s) of new features and bugfixes (if the feature doesn't require root)
- [x] Check for documentation, if needed
- [x] Check for version history, if needed
- [x] Check BaTLab dashboard for successful build (https://batlab.chtc.wisc.edu/results/workspace.php) and test for either the PR or a workspace build by the developer that has the Jira ticket as a comment.
- [x] Check that commit message references the Jira ticket (HTCONDOR-xxx)

## After the above
- Hit the merge button if the pull request is approved and it is not a security patch (security changes require 2 additional reviews)
- If the pull request is approved, take the ticket out of review state
- Assign JIRA Ticket back to the developer

### CODE REVIEW

**Review by bbockelm — COMMENTED** [review]
A few notes:

- Obviously, there's a merge conflict right now.  That's simple to fix.
- Actually handling the versions correctly for non-negotiated sessions looks great!  I don't have a good test setup for this.  Are you feeling confident in that bit of code or should I go start configuring something?
- For non-AES security, there's a downgrade attack - by manipulating the handshake the attacker can force the client to turn off replay protection.  For AES, handshake manipulations are detected and cause errors.
- Note `Condor_Crypt_Base::randomHexKey` generates a secret, not a key.  This is a weakness of this function in general and could be addressed separately if desired.

bbeec14fc0d2ac6ca23406919623a39b6a4cac4b is worrisome.  It indicates there's at least one piece of code (python-bindings) that not only triggers a resumption in a synchronous mode but also critically depends on the fact that session resumption is non-blocking to function.  Is there a good way to check for other landmines?

**Comment by bbockelm** [comment]
Argh, scratch that comment about `randomHexKey`; it's not a derived secret, it's fine as-is for key generation.

**Comment by JaimeFrey** [comment]
I am confident in the code for handling peer versions with non-negotiated sessions.  The really tricky bit is a session generated by the client where there can be version skew. The only case of that is the startd using the claim session to send an ALIVE or RELEASE_CLAIM message to the schedd. I have tested it with new and old peers.

**Comment by JaimeFrey** [comment]
Concerning the downgrade attack, replay protection isn't available at all with non-AES encryption, as far as I can see. The security handshake on a resumed session is never encrypted or integrity checked with non-AES encryption, so the nonces don't do anything.

**Comment by JaimeFrey** [comment]
I'll have to think about how we could audit the code for other instances like https://github.com/htcondor/htcondor/commit/bbeec14fc0d2ac6ca23406919623a39b6a4cac4b

**Review by bbockelm — APPROVED** [review]
LGTM now the merge conflict is fixed.

In terms of finding places this could cause problems, I believe Mark and/or @tannenba once made a spreadsheet of all commands and annotated which ones are "one-way".  One could read through those and take a guess if any would be done concurrent with another command, leading to deadlock.

Can't really come up with scenarios beyond reschedule -- but also not sure I would have thought of the reschedule scenario either.

**Pull request merged**
