### PR TITLE
Replace distutils.sysconfig with sysconfig

### PR DESCRIPTION
**Pull request by duncanmmacleod**
This PR replaces all uses of Python 3's `distutils.sysconfig` with `sysconfig`, `distutils` is slated for removal in Python 3.12.

I am confident that the relevant replacements should produce identical results for all supported versions of Python 3 (tested back to 3.6). This can be checked with the following script:

```python
from distutils import sysconfig

old = [
    sysconfig.get_python_inc(plat_specific=True),
    sysconfig.get_config_var('LIBDIR'),
    sysconfig.get_config_var('MULTIARCH'),
    sysconfig.get_config_var('LDLIBRARY'),
    sysconfig.get_python_lib(plat_specific=True, prefix=''),
    sysconfig.get_config_var('SO'),
]

import sysconfig

new = [
    sysconfig.get_path('platinclude'),
    sysconfig.get_config_var('LIBDIR'),
    sysconfig.get_config_var('MULTIARCH'),
    sysconfig.get_config_var('LDLIBRARY'),
    sysconfig.get_path('platlib', vars={'platbase': ''}).lstrip('/'),
    sysconfig.get_config_var('EXT_SUFFIX'),
]

for o, n in zip(old, new):
    print(f"Comparing")
    print(f"  {o}")
    print(f"  {n}")
    assert o == n
```

# HTCondor Pull Request Checklist for internal reviewers

- [ ] Verify that (GitHub thinks) the merge is clean. If it isn't, and you're confident you can resolve the conflicts, do so. Otherwise, send it back to the original developer.
- [ ] Verify that the related Jira ticket exists and has a target version number and that it is correct.
- [ ] Verify that the Jira ticket is in review status and is assigned to the reviewer.
- [ ] Verify that the Jira ticket (HTCONDOR-xxx) is mentioned at the beginning of the title. Edit it, if not
- [ ] Verify that the branch destination of the PR matches the target version of the ticket
- [ ] Check for correctness of change
- [ ] Check for regression test(s) of new features and bugfixes (if the feature doesn't require root)
- [ ] Check for documentation, if needed
- [ ] Check for version history, if needed
- [ ] Check BaTLab dashboard for successful build (https://batlab.chtc.wisc.edu/results/workspace.php) and test for either the PR or a workspace build by the developer that has the Jira ticket as a comment.
- [ ] Check that each commit message references the Jira ticket (HTCONDOR-xxx)

## After the above
- Hit the merge button if the pull request is approved and it is not a security patch (security changes require 2 additional reviews)
- If the pull request is approved, take the ticket out of review state
- Assign JIRA Ticket back to the developer

### CODE REVIEW

**Comment by timtheisen** [comment]
The PR fails on Debian, Ubuntu, MacOS, and Windows.

**Comment by duncanmmacleod** [comment]
> The PR fails on Debian, Ubuntu, MacOS, and Windows.

@timtheisen, are those build logs visible to me?

**Comment by GregThain** [comment]
So, here's the problem with the mac builds in the HTCondor CI system:

```
batlab-mac-1:__build gthain$ /usr/bin/python3 -c "import sysconfig;print(sysconfig.get_path('platinclude')[1:])"
Library/Python/3.8/include
batlab-mac-1:__build gthain$ /usr/bin/python3 -c "from distutils import sysconfig;print(sysconfig.get_python_inc(plat_specific=True))"
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/include/python3.8
```

Later on, the build of boost fails, looking for pyconfig.h in this directory.

**Comment by jasoncpatton** [comment]
Latest discussion with @GregThain is to try using CMake's latest `FindPackage()`, which seems to be able to find the right include dir in brief testing.

**Comment by GregThain** [comment]
Running python ourselves in cmake to discovery paths seems like a loosing strategy.  We're fixing this problem with python 3.12 with [PR-1026](https://github.com/htcondor/htcondor/pull/1026 )  If HTCondor builds in conda-forge with that PR, I'd like to close this one.

**Comment by jasoncpatton** [comment]
Closing with the merge of #1026, can re-open if switching to CMake's `FindPackage` machinery causes any problems.

**Pull request closed without merging**
