### PR TITLE
Fixups for TOFU mode.  HTCONDOR-1455

### PR DESCRIPTION
**Pull request by bbockelm**
This puts in a few improvements to TOFU mode:

- Set OpenSSL flag to make generated key usable in a TLS connection.
- Auto-generate in a HTCondor-specific location, avoiding touching system files.
- Treat the cert/key config parameter as a list; iterate down the list until an existing file pair is found.
- Enable bootstrapping by default.

# HTCondor Pull Request Checklist for internal reviewers

- [ ] Verify that (GitHub thinks) the merge is clean. If it isn't, and you're confident you can resolve the conflicts, do so. Otherwise, send it back to the original developer.
- [ ] Verify that the related Jira ticket exists and has a target version number and that it is correct.
- [ ] Verify that the Jira ticket is in review status and is assigned to the reviewer.
- [ ] Verify that the Jira ticket (HTCONDOR-xxx) is mentioned at the beginning of the title. Edit it, if not
- [ ] Verify that the branch destination of the PR matches the target version of the ticket
- [ ] Check for correctness of change
- [ ] Check for regression test(s) of new features and bugfixes (if the feature doesn't require root)
- [ ] Check for documentation, if needed
- [ ] Check for version history, if needed
- [ ] Check BaTLab dashboard for successful build (https://batlab.chtc.wisc.edu/results/workspace.php) and test for either the PR or a workspace build by the developer that has the Jira ticket as a comment.
- [ ] Check that each commit message references the Jira ticket (HTCONDOR-xxx)

## After the above
- Hit the merge button if the pull request is approved and it is not a security patch (security changes require 2 additional reviews)
- If the pull request is approved, take the ticket out of review state
- Assign JIRA Ticket back to the developer

### CODE REVIEW

**Comment by GregThain** [comment]
Note that this breaks most of the tests on Windows.

**Comment by bbockelm** [comment]
@GregThain - looks like there's a fairly immediate on Windows when `COLLECTOR_BOOTSTRAP_SSL_CERTIFICATE` is set to True (current default is false).

The collector immediately exits 1 (is that a segfault on Windows?) with the last line indicating it did so while writing out the bootstrap CA.  Almost nothing in this PR changes the CA creation code, just the default - meaning the segfault is likely lingering in the production code.

I do not have access to a Windows host.  Can you do a quick spot-check and see what the segfault is?

I suppose I could change the Windows default to remain off but I don't see much value in punting...

**Comment by GregThain** [comment]
On 12/3/22 8:27 AM, Brian P Bockelman wrote:
>
> @GregThain <https://github.com/GregThain> - looks like there's a 
> fairly immediate on Windows when |COLLECTOR_BOOTSTRAP_SSL_CERTIFICATE| 
> is set to True (current default is false).
>
I can't log into the Windows machines, either, I believe only TJ can, 
via remote desktop.

**Review by JaimeFrey — APPROVED** [review]
The changes look good to me. I want to do some more testing, particularly for the windows failures, and update the docs before this goes into main. As such, I'm merging into a new topic branch on the central repository that I will make some additional changes on before a final merge.

**Pull request merged**
