### PR TITLE
HTCONDOR-890: Check if using VOMS before searching for libs

### PR DESCRIPTION
**Pull request by jasoncpatton**
# HTCondor Pull Request Checklist for internal reviewers

- [x] Verify that (GitHub thinks) the merge is clean. If it isn't, and you're confident you can resolve the conflicts, do so. Otherwise, send it back to the original developer.
- [x] Verify that the related Jira ticket exists and has a target version number and that it is correct.
- [x] Verify that the Jira ticket is in review status and is assigned to the reviewer.
- [x] Verify that the Jira ticket (HTCONDOR-xxx) is mentioned at the beginning of the title. Edit it, if not
- [x] Verify that the branch destination of the PR matches the target version of the ticket
- [x] Check for correctness of change
- [x] Check for regression test(s) of new features and bugfixes (if the feature doesn't require root)
- [x] Check for documentation, if needed
- [x] Check for version history, if needed
- [x] Check BaTLab dashboard for successful build (https://batlab.chtc.wisc.edu/results/workspace.php) and test for either the PR or a workspace build by the developer that has the Jira ticket as a comment.
- [x] Check that commit message references the Jira ticket (HTCONDOR-xxx)

## After the above
- Hit the merge button if the pull request is approved and it is not a security patch (security changes require 2 additional reviews)
- If the pull request is approved, take the ticket out of review state
- Assign JIRA Ticket back to the developer

### CODE REVIEW

**Comment by timtheisen** [comment]
The build passes in the BaTLab, but blew up on the new Mac github runner.

**Review by timtheisen — CHANGES_REQUESTED** [review]
For some reason, this crashes on the newer Mac builds that are started by github. I can't merge it when those builds are failing.

**Comment by timtheisen** [comment]
@JaimeFrey Do you have an idea why this change causes build failures on the Mac github runner.

**Comment by JaimeFrey** [comment]
It appears that the GitHub runner is setting PROPER to true for the macOS build. Our Globus cmake files assume PROPER will be true for linux only, and call find_so_name(), which only works on linux. This isn't an issue for PRs merging to master, where Globus is disabled. I looked at other recent PRs merging to V9_0-branch and they don't have a GitHub runner. Was this changed recently?

**Comment by bbockelm** [comment]
@JaimeFrey - Tim changed the base branch from `master` to `V9_0-branch` after the PR was created.  The action was kicked off on trying to merge the branch to master.  It seems the outcome was GitHub used the master build instructions against a V9_0-based branch -- hilarity ensues.

Here's the question though -- what did BatLab test?  The bare branch?  Or the branch after it was merged with many commits from master?

One could probably read through the code and figure that out.  I'd suggest simply opening a new clean branch on the right base.

**Comment by timtheisen** [comment]
@JaimeFrey : Thank you for the analysis. It's fine for this to be based against master. (It will fold into the LTS in the spring) I don't want to waste any more time on this.

**Review by timtheisen — APPROVED** [review]

**Pull request merged**
