### PR TITLE
HTCONDOR-1096: Fix up date format for generating Docker images

### PR DESCRIPTION
**Pull request by timtheisen**
https://opensciencegrid.atlassian.net/browse/HTCONDOR-969

# HTCondor Pull Request Checklist for internal reviewers

- [x] Verify that (GitHub thinks) the merge is clean. If it isn't, and you're confident you can resolve the conflicts, do so. Otherwise, send it back to the original developer.
- [x] Verify that the related Jira ticket exists and has a target version number and that it is correct.
- [x] Verify that the Jira ticket is in review status and is assigned to the reviewer.
- [x] Verify that the Jira ticket (HTCONDOR-xxx) is mentioned at the beginning of the title. Edit it, if not
- [x] Verify that the branch destination of the PR matches the target version of the ticket
- [x] Check for correctness of change
- [x] Check for regression test(s) of new features and bugfixes (if the feature doesn't require root)
- [x] Check for documentation, if needed
- [x] Check for version history, if needed
- [x] Check BaTLab dashboard for successful build (https://batlab.chtc.wisc.edu/results/workspace.php) and test for either the PR or a workspace build by the developer that has the Jira ticket as a comment.
- [ ] Check that commit message references the Jira ticket (HTCONDOR-xxx)

## After the above
- Hit the merge button if the pull request is approved and it is not a security patch (security changes require 2 additional reviews)
- If the pull request is approved, take the ticket out of review state
- Assign JIRA Ticket back to the developer

### CODE REVIEW

**Comment by timtheisen** [comment]
I put this under the general cleanup because it is an internal script, so no version history. And, I fixed the script as I was releasing the 9.7.0 release.

**Comment by matyasselmeci** [comment]
Can you change it so that it works with the old format too, so we can build images for the LTS series?

**Comment by timtheisen** [comment]
I was running the script from the V9_0-branch to general the V9_0 images. Is that not correct? That's why I didn't make it more complicated here.

**Comment by matyasselmeci** [comment]
I've always run the script from master regardless of the version of the image I want to generate; the software is installed from rpms or debs based on arguments, so the checked out branch doesn't determine the version.

If you want to have separate branches of the script for 9.0 vs 9.x, I suggest making sure you can't accidentally build 9.x containers with the 9.0 script or vice versa!

**Comment by timtheisen** [comment]
@matyasselmeci This tries the new date format and fallsback to the old if necessary.

**Comment by matyasselmeci** [comment]
The code looks good to me except the ticket this references [HTCONDOR-969](https://opensciencegrid.atlassian.net/browse/HTCONDOR-969), was labeled for 9.8.0 and is marked as done. You might want to make a new branch that refers to a different ticket, cherry-pick these commits and change the commit messages, and probably make a new PR that references this one.

**Comment by timtheisen** [comment]
@matyasselmeci That's too much effort for this minor change. I'll change the PR name to match the code cleanup Jira ticket for 9.10 and that will be sufficieent.

**Comment by matyasselmeci** [comment]
OK, your call.

**Review by matyasselmeci — APPROVED** [review]

**Pull request merged**
