### PR TITLE
HTCONDOR-638 Provide remote administration capability in daemon ads

### PR DESCRIPTION
**Pull request by JaimeFrey**
https://opensciencegrid.atlassian.net/browse/HTCONDOR-638

# HTCondor Pull Request Checklist for internal reviewers

- [x] Verify that (GitHub thinks) the merge is clean. If it isn't, and you're confident you can resolve the conflicts, do so. Otherwise, send it back to the original developer.
- [x] Verify that the related Jira ticket exists and has a target version number and that it is correct.
- [x] Verify that the Jira ticket is in review status and is assigned to the reviewer.
- [x] Verify that the Jira ticket (HTCONDOR-xxx) is mentioned at the beginning of the title. Edit it, if not
- [x] Verify that the branch destination of the PR matches the target version of the ticket
- [x] Check for correctness of change
- [x] Check for regression test(s) of new features and bugfixes (if the feature doesn't require root)
- [x] Check for documentation, if needed
- [x] Check for version history, if needed
- [x] Check BaTLab dashboard for successful build (https://batlab.chtc.wisc.edu/results/workspace.php) and test for either the PR or a workspace build by the developer that has the Jira ticket as a comment.
- [x] Check that commit message references the Jira ticket (HTCONDOR-xxx)

## After the above
- Hit the merge button if the pull request is approved and it is not a security patch (security changes require 2 additional reviews)
- If the pull request is approved, take the ticket out of review state
- Assign JIRA Ticket back to the developer

### CODE REVIEW

**Review by bbockelm — COMMENTED** [review]
One big picture question on this is the removal of the "private attributes V2".

Seems we're digging the hole deeper by adding another set of one-off handling (if nothing else, this makes the hashtable lookup infinitesimally slower instead of doing a fixed-cost prefix match).

You mentioned that you had an alternate approach (I assume some sort of per-instance encyrption instead of process-wide?).  Is it reasonable to tackle that first and then merge this one?

**Comment by JaimeFrey** [comment]
In avoiding a new private attribute prefix, I wanted to avoid digging a second hole that would also be abandoned. I also wanted to avoid the "do I send V1 and/or V2 private attributes" based on client version, which was getting complex in putClassAd(). I don't have a concrete plan for "the right way" to handle private attributes to/from/in the collector, so I'm reconsidering the decision to avoid introducing the private prefix to attribute names.

**Comment by JaimeFrey** [comment]
My ideal is for get/putClassAd() to not care about private attributes. Currently, these functions need to know about private attributes in order to selectively encrypt them when encryption is disabled with the older algorithms and to filter them out in daemon ads going to/from the collector (daemons filtering when sending to old collectors and the collector filtering when sending to old or non-privileged clients).
For the former, we'll have to wait until we can dump the old encryption algorithms (or start requiring encryption for all connections). For the latter, I'm thinking about a variation of the startd's private ad, where the collector puts the private attributes into a second ad that's not directly queryable. For authorized clients that request it, the private attributes can be added to query results. Advertising daemons could put all private attributes in a specially-named nested ad. That makes it quick and easy for the collector to separate them at ingestion time (no need to examine every attribute name).

**Comment by JaimeFrey** [comment]
HTCONDOR-183 has my proposal for protecting private attributes inside the collector. I've re-added the V2 private attributes name prefix. Brian, do you have any other concerns with the current state of this PR?

**Review by bbockelm — APPROVED** [review]
LGTM.

Running through a few ctests and sanity tests locally and then will merge.

**Pull request merged**
