### PR TITLE
HTCONDOR-2145: Get ce-audit plugin to build on openSUSE

### PR DESCRIPTION
**Pull request by timtheisen**
<Insert PR description here, and leave checklist below for code review.>

# HTCondor Pull Request Checklist for internal reviewers

- [ ] Verify that (GitHub thinks) the merge is clean. If it isn't, and you're confident you can resolve the conflicts, do so. Otherwise, send it back to the original developer.
- [ ] Verify that the related Jira ticket exists and has a target version number and that it is correct.
- [ ] Verify that the Jira ticket is in review status and is assigned to the reviewer.
- [ ] Verify that the Jira ticket (HTCONDOR-xxx) is mentioned at the beginning of the title. Edit it, if not
- [ ] Verify that the branch destination of the PR matches the target version of the ticket
- [ ] Check for correctness of change
- [ ] Check for regression test(s) of new features and bugfixes (if the feature doesn't require root)
- [ ] Check for documentation, if needed  (documentation [build logs](https://readthedocs.org/projects/htcondor/builds/))
- [ ] Check for version history, if needed
- [ ] Check BaTLab dashboard for successful build (https://batlab.chtc.wisc.edu/results/workspace.php) and test for either the PR or a workspace build by the developer that has the Jira ticket as a comment.
- [ ] Check that each commit message references the Jira ticket (HTCONDOR-xxx)

## After the above
- Hit the merge button if the pull request is approved and it is not a security patch (security changes require 2 additional reviews)
- If the pull request is approved, take the ticket out of review state
- Assign JIRA Ticket back to the developer

### CODE REVIEW

**Comment by timtheisen** [comment]
@GregThain This change got the ce-audit plugin to build on openSUSE. Is this correct?

**Comment by GregThain** [comment]
I'm curious why we only need this on opensuse -- what was the error?

**Comment by timtheisen** [comment]
`/usr/bin/g++-11 -fPIC -O2 -g -m64 -fmessage-length=0 -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -DNDEBUG -fcoroutines -fopenmp -O2 -g -m64 -fmessage-length=0 -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -DNDEBUG -fPIC -fopenmp -Wall -W -Wextra -Wfloat-equal -Wendif-labels -Wpointer-arith -Wcast-qual -Wcast-align -Wvolatile-register-var -Wno-error=unused-local-typedefs -Wdeprecated-declarations -Wno-error=deprecated-declarations -Wno-nonnull-compare -Wno-error=nonnull-compare -fstack-protector -O2 -g3 -DNDEBUG  -Wl,--as-needed -Wl,--no-undefined -Wl,-z,now  -Wl,-z,relro -Wl,--enable-new-dtags -shared -Wl,-soname,ce-audit.so -o ce-audit.so CMakeFiles/ce-audit.dir/ce-audit-plugin.cpp.o  ../condor_utils/libcondor_utils_23_0_3.so -lrt ../classad/libclassad.so.23.0.3 /usr/lib64/libpcre2-8.so -ldl /usr/lib64/libcrypto.so /usr/lib64/libuuid.so 
/usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/ce-audit.dir/ce-audit-plugin.cpp.o: in function `CEAuditPlugin::CEAuditPlugin()':
/home/tim/build/build-VoWMq8/BUILD/condor-23.0.3/src/condor_collector.V6/ce-audit-plugin.cpp:14:(.text+0x225): undefined reference to `CollectorPlugin::CollectorPlugin()'
/usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/ce-audit.dir/ce-audit-plugin.cpp.o: in function `CEAuditPlugin::~CEAuditPlugin()':
/home/tim/build/build-VoWMq8/BUILD/condor-23.0.3/src/condor_collector.V6/ce-audit-plugin.cpp:18:(.text+0x1f0): undefined reference to `CollectorPlugin::~CollectorPlugin()'
/usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/ce-audit.dir/ce-audit-plugin.cpp.o:(.data.rel.ro._ZTI13CEAuditPlugin[_ZTI13CEAuditPlugin]+0x10): undefined reference to `typeinfo for CollectorPlugin'
collect2: error: ld returned 1 exit status
`

**Comment by timtheisen** [comment]
New PR with correct ticket number: #1991

**Pull request closed without merging**
