### PR TITLE
Fix vault documentation links

### PR DESCRIPTION
**Pull request by DrDaveD**
This improves the vault documentation.  The changes are in a section that does not show by default at htcondor.readthedocs.io but I made an htcondor-vault.readthedocs.io where [these changes](https://htcondor-vault.readthedocs.io/en/latest/admin-manual/setting-up-special-environments.html#using-vault-as-the-oauth-client) are already tested.

### CODE REVIEW

**Comment by DrDaveD** [comment]
@jasoncpatton Please review.

**Review by timtheisen — CHANGES_REQUESTED** [review]
This refers to gitub.com

Please fix.

**Comment by DrDaveD** [comment]
Good catch, fixed.

**Review by jasoncpatton — COMMENTED** [review]
Looks good, merging...

**Pull request merged**
