### PR TITLE
HTCONDOR-2166 Adstash now uses multiprocessing spawn method

### PR DESCRIPTION
**Pull request by jasoncpatton**
https://opensciencegrid.atlassian.net/browse/HTCONDOR-2166

# HTCondor Pull Request Checklist for internal reviewers

- [x] Verify that (GitHub thinks) the merge is clean. If it isn't, and you're confident you can resolve the conflicts, do so. Otherwise, send it back to the original developer.
- [x] Verify that the related Jira ticket exists and has a target version number and that it is correct.
- [ ] Verify that the Jira ticket is in review status and is assigned to the reviewer.
- [x] Verify that the Jira ticket (HTCONDOR-xxx) is mentioned at the beginning of the title. Edit it, if not
- [x] Verify that the branch destination of the PR matches the target version of the ticket
- [x] Check for correctness of change
- [ ] Check for regression test(s) of new features and bugfixes (if the feature doesn't require root)
- [ ] Check for documentation, if needed  (documentation [build logs](https://readthedocs.org/projects/htcondor/builds/))
- [x] Check for version history, if needed
- [x] Check BaTLab dashboard for successful build (https://batlab.chtc.wisc.edu/results/workspace.php) and test for either the PR or a workspace build by the developer that has the Jira ticket as a comment.
- [x] Check that each commit message references the Jira ticket (HTCONDOR-xxx)

## After the above
- Hit the merge button if the pull request is approved and it is not a security patch (security changes require 2 additional reviews)
- If the pull request is approved, take the ticket out of review state
- Assign JIRA Ticket back to the developer

### CODE REVIEW

**Comment by jasoncpatton** [comment]
@ColeBollig Hold off on merging this, I missed a critical step...

**Comment by jasoncpatton** [comment]
> @ColeBollig Hold off on merging this, I missed a critical step...

Ok, _now_ this is ready.

**Comment by jasoncpatton** [comment]
> There was a build error on AmazonLinux2023 and I can't tell if this is an issue pertaining to the PR or not

Looks like a spurious OOM during the build, I think it can be ignored.

**Review by ColeBollig — APPROVED** [review]
LGTM, Want to note that the AmazonLinux2023 build was killed due to memory usage. Seems unrelated to changes

**Pull request merged**
