### PR TITLE
HTCONDOR-1377: condor_preen deleting important core files

### PR DESCRIPTION
**Pull request by ColeBollig**
-Changed PREEN_COREFILE_MAX_SIZE from int to long long to allow
 specification of file size maximums greater than 2GB
-Modified condor_preen to check large core files for if they
 belong to certain daemons (Schedd, Negotiator, Collector) it
 checks all core files from newest to oldest for the total space
 to be under a max sum.
     -Added hidden knobs for these max sums:
          -PREEN_SCHEDD_COREFILES_MAX_SUM
          -PREEN_NEGOTIATOR_COREFILES_MAX_SUM
          -PREEN_COLLECTOR_COREFILES_MAX_SUM
-Fixed spelling error for core file stale age knob.

<Insert PR description here, and leave checklist below for code review.>

# HTCondor Pull Request Checklist for internal reviewers

- [ ] Verify that (GitHub thinks) the merge is clean. If it isn't, and you're confident you can resolve the conflicts, do so. Otherwise, send it back to the original developer.
- [ ] Verify that the related Jira ticket exists and has a target version number and that it is correct.
- [ ] Verify that the Jira ticket is in review status and is assigned to the reviewer.
- [ ] Verify that the Jira ticket (HTCONDOR-xxx) is mentioned at the beginning of the title. Edit it, if not
- [ ] Verify that the branch destination of the PR matches the target version of the ticket
- [ ] Check for correctness of change
- [ ] Check for regression test(s) of new features and bugfixes (if the feature doesn't require root)
- [ ] Check for documentation, if needed
- [ ] Check for version history, if needed
- [ ] Check BaTLab dashboard for successful build (https://batlab.chtc.wisc.edu/results/workspace.php) and test for either the PR or a workspace build by the developer that has the Jira ticket as a comment.
- [ ] Check that each commit message references the Jira ticket (HTCONDOR-xxx)

## After the above
- Hit the merge button if the pull request is approved and it is not a security patch (security changes require 2 additional reviews)
- If the pull request is approved, take the ticket out of review state
- Assign JIRA Ticket back to the developer

### CODE REVIEW

**Review by johnkn — APPROVED** [review]
Looks good

**Comment by timtheisen** [comment]
Why was this merge into main when the target is 10.0.0?

**Comment by johnkn** [comment]
sigh.

**Comment by timtheisen** [comment]
I can fix it.

**Comment by ColeBollig** [comment]
@timtheisen I forgot to change to the PR to be against v10.0.0 and it appears that TJ missed this. A bit of both of us forgetting to check it was against the correct branch sorry. Shou

**Comment by timtheisen** [comment]
Fixed.

**Pull request merged**
