### PR TITLE
HTCONDOR-1021 HTCondor CLI checks if annex enabled

### PR DESCRIPTION
**Pull request by jasoncpatton**
https://opensciencegrid.atlassian.net/browse/HTCONDOR-1021

# HTCondor Pull Request Checklist for internal reviewers

- [ ] Verify that (GitHub thinks) the merge is clean. If it isn't, and you're confident you can resolve the conflicts, do so. Otherwise, send it back to the original developer.
- [ ] Verify that the related Jira ticket exists and has a target version number and that it is correct.
- [ ] Verify that the Jira ticket is in review status and is assigned to the reviewer.
- [ ] Verify that the Jira ticket (HTCONDOR-xxx) is mentioned at the beginning of the title. Edit it, if not
- [ ] Verify that the branch destination of the PR matches the target version of the ticket
- [ ] Check for correctness of change
- [ ] Check for regression test(s) of new features and bugfixes (if the feature doesn't require root)
- [ ] Check for documentation, if needed
- [ ] Check for version history, if needed
- [ ] Check BaTLab dashboard for successful build (https://batlab.chtc.wisc.edu/results/workspace.php) and test for either the PR or a workspace build by the developer that has the Jira ticket as a comment.
- [ ] Check that commit message references the Jira ticket (HTCONDOR-xxx)

## After the above
- Hit the merge button if the pull request is approved and it is not a security patch (security changes require 2 additional reviews)
- If the pull request is approved, take the ticket out of review state
- Assign JIRA Ticket back to the developer

### CODE REVIEW

**Comment by jasoncpatton** [comment]
@Todd-L-Miller any more that needs to be done for this? Not sure how I feel about restricting access to `htcondor annex shutdown` e.g. if an admin happens to flip the switch while some user's annex is still running, but also seems silly to have it try to access the annex collector (especially given the default value we have coded) if it's not enabled.

**Comment by jasoncpatton** [comment]
Also, should this be targeting `master` or `V9_8_0-branch`?

**Comment by Todd-L-Miller** [comment]
It should be targeting `V9_8_0-branch`, sadly.

**Comment by Todd-L-Miller** [comment]
I agree that the situation where an administrator turns this off while a user still has a live annex would suck, but if they took the collector away, at least the annex will shut itself down once its jobs complete.

**Comment by Todd-L-Miller** [comment]
Finally -- this doesn't appear to flag the `--annex-name` code in `htcondor job submit`, which it probably should.

**Comment by jasoncpatton** [comment]
> Finally -- this doesn't appear to flag the `--annex-name` code in `htcondor job submit`, which it probably should.

I thought what you did in #503 covered this case?

https://github.com/htcondor/htcondor/blob/681bc10c06182052928ed1c47916b408e4be1e7d/src/condor_tools/htcondor_cli/job.py#L74-L79

(We could move the check earlier, though.)

**Comment by jasoncpatton** [comment]
I messed up the commit history trying to get this to merge correctly with `V9_8_0-branch`, moving PR to #527 .

**Pull request closed without merging**
