### PR TITLE
Review src/condor_scripts/get_htcondor (HTCONDOR-265)

### PR DESCRIPTION
**Pull request by edquist**
Attn @Todd-L-Miller,

I didn't see outright bugs with the get_htcondor script, but there were some areas where I felt like simplifications / cleanup were in order.

Feel free to step through these commits for details.

Also some notes for bash in general that I have not changed everywhere in the script, but you may want to consider:

For `#!/bin/bash` scripts (like this one) :

- `[[ $var ]]` is equivalent to `[ -n "$var" ]`, and a bit nicer in that you don't have to quote variables

- Likewise, `[ -z "$var" ]` is the same as `[[ ! $var ]]` or `! [[ $var ]]`

- In `case $var`, `$var` does not need to be quoted

- Nor the `value)` strings within `case` blocks

- In `var=value`, `value` does not need to be quoted (quotes are only necessary for literal strings with whitespace)

- Neither does `var=${some}${expression}${with}${variables}` (even if the variables contain whitespace)

- Nor `var=$(some command line)` (even if the output contains whitespace)

- Some logic can be condensed if you add a `fail` function, like
```
fail () { echo "$@"; exit 1; }  # optionally redirect echo to stderr with >&2
```

And then blocks like

```
if [ -z "$var" ]; then
    echo "failure message"
    exit 1
fi
```

can be replaced with

```
[[ $var ]] || fail "failure message"
```

### CODE REVIEW

**Review by Todd-L-Miller — COMMENTED** [review]
The following was supposed to be attached to 09276ca707376281a9222dfb08089036e820662f, not sure why that didn't happen.
Rejected: _get_htcondor_ sets `-e` immediately, and `shift` when `$#` is `0` is an error.

**Comment by edquist** [comment]
> The following was supposed to be attached to [09276ca](https://github.com/htcondor/htcondor/commit/09276ca707376281a9222dfb08089036e820662f), not sure why that didn't happen.
> Rejected: _get_htcondor_ sets `-e` immediately, and `shift` when `$#` is `0` is an error.

Yeah but that statement is in a `while [ $# -gt 0 ]` block, and as far as I can tell, further `shift` commands are only issued when there is an extra arg to shift off from `$2`

**Review by Todd-L-Miller — COMMENTED** [review]
Rejecting 21f6812870db0705aa2a3ee89097b617dc0670c5 in favor of something like 150e4fc5989c9bd0ae2dece7988373707ee80cdf, except without the part where it'll break everything by being in the wrong case.

**Comment by Todd-L-Miller** [comment]
> 
> 
> > The following was supposed to be attached to [09276ca](https://github.com/htcondor/htcondor/commit/09276ca707376281a9222dfb08089036e820662f), not sure why that didn't happen.
> > Rejected: _get_htcondor_ sets `-e` immediately, and `shift` when `$#` is `0` is an error.
> 
> Yeah but that statement is in a `while [ $# -gt 0 ]` block, and as far as I can tell, further `shift` commands are only issued when there is an extra arg to shift off from `$2`

Oh, hey, I missed that.  I'll take another look.

**Comment by Todd-L-Miller** [comment]
This was resolved offline.

**Pull request closed without merging**
