### PR TITLE
HTCONDOR-1972 Add permissions check for credential files

### PR DESCRIPTION
**Pull request by jasoncpatton**
https://opensciencegrid.atlassian.net/browse/HTCONDOR-1972

# HTCondor Pull Request Checklist for internal reviewers

- [x] Verify that (GitHub thinks) the merge is clean. If it isn't, and you're confident you can resolve the conflicts, do so. Otherwise, send it back to the original developer.
- [x] Verify that the related Jira ticket exists and has a target version number and that it is correct.
- [x] Verify that the Jira ticket is in review status and is assigned to the reviewer.
- [x] Verify that the Jira ticket (HTCONDOR-xxx) is mentioned at the beginning of the title. Edit it, if not
- [x] Verify that the branch destination of the PR matches the target version of the ticket
- [x] Check for correctness of change
- [x] Check for regression test(s) of new features and bugfixes (if the feature doesn't require root)
- [ ] Check for documentation, if needed  (documentation [build logs](https://readthedocs.org/projects/htcondor/builds/))
- [ ] Check for version history, if needed
- [x] Check BaTLab dashboard for successful build (https://batlab.chtc.wisc.edu/results/workspace.php) and test for either the PR or a workspace build by the developer that has the Jira ticket as a comment.
- [x] Check that each commit message references the Jira ticket (HTCONDOR-xxx)

## After the above
- Hit the merge button if the pull request is approved and it is not a security patch (security changes require 2 additional reviews)
- If the pull request is approved, take the ticket out of review state
- Assign JIRA Ticket back to the developer

### CODE REVIEW

**Comment by jasoncpatton** [comment]
In addition to passing the test suite, a quick test of the bundled test script in an interactive job with a token `scitokens.use` seems to spit out the expected stderr text:

```shell
[jcpatton@build4002 ~]$ cat test_script.sh 
#!/bin/bash
tokenfiles=($@)
cat ${tokenfiles[@]/#/$_CONDOR_CREDS/}
ls $_CONDOR_CREDS >/dev/null 2>&1 || \
    >&2 echo 'Could not list $_CONDOR_CREDS:' "$(stat -L -c "%A %u %g" $_CONDOR_CREDS) (I am $(id -u) with group $(id -g))"
for tokenfile in $tokenfiles; do
    tokenpath="$_CONDOR_CREDS/$tokenfile"
    [ "$(id -u)" -eq "$(stat -L -c "%u" "$tokenpath")" ] || \
        >&2 echo "Bad ownership of $tokenfile: $(stat -L -c "%A %u %g" $tokenpath) (I am $(id -u) with group $(id -g))"
    tokenperms=$(stat -L -c "%a" "$tokenpath")
    [ "${tokenperms:0-2}" -eq "00" ] || \
        >&2 echo "Bad permissions on $tokenfile: $(stat -L -c "%A %u %g" $tokenpath) (I am $(id -u) with group $(id -g))"
done
[jcpatton@build4002 ~]$ ./test_script.sh scitokens.use >out 2>err
[jcpatton@build4002 ~]$ cat err
[jcpatton@build4002 ~]$ chmod 777 $_CONDOR_CREDS/scitokens.use
[jcpatton@build4002 ~]$ ./test_script.sh scitokens.use >out 2>err
[jcpatton@build4002 ~]$ cat err
Bad permissions on scitokens.use: -rwxrwxrwx 21356 21356 (I am 21356 with group 21356)
[jcpatton@build4002 ~]$ chmod 700 $_CONDOR_CREDS/scitokens.use
[jcpatton@build4002 ~]$ ./test_script.sh scitokens.use >out 2>err
[jcpatton@build4002 ~]$ cat err
```

**Review by joereuss12 — COMMENTED** [review]
LGTM, assigning back to you for changes I made to the ornithology test

**Review by jasoncpatton — COMMENTED** [review]
LGTM @joereuss12 ... I cannot approve my own PR though.

**Review by joereuss12 — APPROVED** [review]
Final check looks good!

**Pull request merged**
