### PR TITLE
(HTCONDOR-1999)  Add longest-prefix-first as an option for map files.

### PR DESCRIPTION
**Pull request by Todd-L-Miller**
This PR allows us to use map files to match against the longest prefix first, instead of just exact matches and regular expressions.

# HTCondor Pull Request Checklist for internal reviewers

- [x] Verify that (GitHub thinks) the merge is clean. If it isn't, and you're confident you can resolve the conflicts, do so. Otherwise, send it back to the original developer.
- [x] Verify that the related Jira ticket exists and has a target version number and that it is correct.
- [x] Verify that the Jira ticket is in review status and is assigned to the reviewer.
- [x] Verify that the Jira ticket (HTCONDOR-xxx) is mentioned at the beginning of the title. Edit it, if not
- [x] Verify that the branch destination of the PR matches the target version of the ticket
- [x] Check for correctness of change
- [ ] Check for regression test(s) of new features and bugfixes (if the feature doesn't require root)
- [ ] Check for documentation, if needed  (documentation [build logs](https://readthedocs.org/projects/htcondor/builds/))
- [ ] Check for version history, if needed
- [x] Check BaTLab dashboard for successful build (https://batlab.chtc.wisc.edu/results/workspace.php) and test for either the PR or a workspace build by the developer that has the Jira ticket as a comment.
- [x] Check that each commit message references the Jira ticket (HTCONDOR-xxx)

## After the above
- Hit the merge button if the pull request is approved and it is not a security patch (security changes require 2 additional reviews)
- If the pull request is approved, take the ticket out of review state
- Assign JIRA Ticket back to the developer

### CODE REVIEW

**Comment by Todd-L-Miller** [comment]
This PR doesn't fully-correctly compute the amount of memory used by the prefix map, but I think that's a diagnostic tool rather than required functionality; we can ask TJ about that.

**Comment by ColeBollig** [comment]
Appears to be unit test failures in regards to the the user mapping

**Review by ColeBollig — APPROVED** [review]
LTGM. Will approve, but is waiting on pending slower build platforms in the batlab

**Comment by timtheisen** [comment]
@ColeBollig I believe that we agreed in dev team to not let the emulated builds slow us down. PRs may be merged after macOS, Windows, and x86_64 Linux build pass.

**Pull request merged**
