### PR TITLE
HTCONDOR-922 job duration limit fixes

### PR DESCRIPTION
**Pull request by JaimeFrey**
https://opensciencegrid.atlassian.net/browse/HTCONDOR-922

# HTCondor Pull Request Checklist for internal reviewers

- [x] Verify that (GitHub thinks) the merge is clean. If it isn't, and you're confident you can resolve the conflicts, do so. Otherwise, send it back to the original developer.
- [x] Verify that the related Jira ticket exists and has a target version number and that it is correct.
- [x] Verify that the Jira ticket is in review status and is assigned to the reviewer.
- [x] Verify that the Jira ticket (HTCONDOR-xxx) is mentioned at the beginning of the title. Edit it, if not
- [x] Verify that the branch destination of the PR matches the target version of the ticket
- [x] Check for correctness of change
- [ ] Check for regression test(s) of new features and bugfixes (if the feature doesn't require root)
- [x] Check for documentation, if needed
- [x] Check for version history, if needed
- [x] Check BaTLab dashboard for successful build (https://batlab.chtc.wisc.edu/results/workspace.php) and test for either the PR or a workspace build by the developer that has the Jira ticket as a comment.
- [x] Check that commit message references the Jira ticket (HTCONDOR-xxx)

## After the above
- Hit the merge button if the pull request is approved and it is not a security patch (security changes require 2 additional reviews)
- If the pull request is approved, take the ticket out of review state
- Assign JIRA Ticket back to the developer

### CODE REVIEW

**Review by Todd-L-Miller — COMMENTED** [review]
Changes look good, but don't have corresponding test cases.  Does it make sense to add them?

**Comment by JaimeFrey** [comment]
I don't think the change to evaluate only for RUNNING or SUSPENDED jobs needs a test case. The added comparison between JobCurrentStartExecutingDate and ShadowBday for AllowedExecuteDuration may deserve one.

**Review by Todd-L-Miller — APPROVED** [review]
OK.  I'll let you decide if the test should be its own ticket.  I've approved the PR but have not done the merge.  If you want to do the test in this PR, just push more changes to it; otherwise, please just record the ticket number in a comment here before pushing the merge button.  Thanks.

**Comment by JaimeFrey** [comment]
I just remembered that the problem I fixed with AllowedExecuteDuration can't trigger at present, since the shadow doesn't do job policy evaluation during input transfer. It starts evaluating the policy when it hears that the job has begun executing. So that fix is future-proofing for if we change when the shadow starts evaluating job policy. Given that, we can't really test it.

**Pull request merged**
