### PR TITLE
Keep copies of overridden Bosco files (SOFTWARE-4125)

### PR DESCRIPTION
**Pull request by brianhlin**
https://opensciencegrid.atlassian.net/browse/SOFTWARE-4125

### CODE REVIEW

**Comment by timtheisen** [comment]
Will this be potentially used to override configuration files? If so, files with the .orig suffix will be processed in the configuration directory. I like the .orig suffix. So, perhaps we should add the .orig suffix to the list of files not processed in the configuration directory.

**Comment by brianhlin** [comment]
@timtheisen yup, OSG Ops commonly uses this feature to override blah config. What config reads `.orig` files? I'm not aware of the blahp doing that at least

**Comment by timtheisen** [comment]
@brianhlin I was thinking of a condor configuration directory. I think that it may be useful to add that to the list of suffixes that will be ignored in a condor configuration directory.

**Review by timtheisen — APPROVED** [review]
Looks good to me

**Review by JaimeFrey — COMMENTED** [review]
Looks good to me.

**Pull request merged**
