### PR TITLE
HTCONDOR-1479-no-special-wheel-cmake

### PR DESCRIPTION
**Pull request by GregThain**
<Insert PR description here, and leave checklist below for code review.>

# HTCondor Pull Request Checklist for internal reviewers

- [ ] Verify that (GitHub thinks) the merge is clean. If it isn't, and you're confident you can resolve the conflicts, do so. Otherwise, send it back to the original developer.
- [ ] Verify that the related Jira ticket exists and has a target version number and that it is correct.
- [ ] Verify that the Jira ticket is in review status and is assigned to the reviewer.
- [ ] Verify that the Jira ticket (HTCONDOR-xxx) is mentioned at the beginning of the title. Edit it, if not
- [ ] Verify that the branch destination of the PR matches the target version of the ticket
- [ ] Check for correctness of change
- [ ] Check for regression test(s) of new features and bugfixes (if the feature doesn't require root)
- [ ] Check for documentation, if needed
- [ ] Check for version history, if needed
- [ ] Check BaTLab dashboard for successful build (https://batlab.chtc.wisc.edu/results/workspace.php) and test for either the PR or a workspace build by the developer that has the Jira ticket as a comment.
- [ ] Check that each commit message references the Jira ticket (HTCONDOR-xxx)

## After the above
- Hit the merge button if the pull request is approved and it is not a security patch (security changes require 2 additional reviews)
- If the pull request is approved, take the ticket out of review state
- Assign JIRA Ticket back to the developer

### CODE REVIEW

**Comment by jasoncpatton** [comment]
The wheel build now fails to detect the correct version of Python during the cmake config:

```
-- The C compiler identification is GNU 10.2.1
-- The CXX compiler identification is GNU 10.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /opt/rh/devtoolset-10/root/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /opt/rh/devtoolset-10/root/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- ***********************************************************
-- System(jcpatton-16766683.0-e1038.chtc.wisc.edu): LINUX(3.10.0-1160.76.1.EL7.X86_64) Arch=X86_64 BitMode=64 BUILDID:UW_Python_Wheel_Build
-- install prefix:/usr/local
-- ********* BEGINNING CONFIGURATION *********
-- Could NOT find Python2 (missing: Python2_INCLUDE_DIRS Python2_LIBRARIES Development Development.Module Development.Embed) (found version "2.7.5")
-- Could NOT find Python3 (missing: Python3_INCLUDE_DIRS Python3_LIBRARIES Development Development.Module Development.Embed) (found version "3.11.0")
```

(In this example, it should have detected 3.8.)

**Comment by jasoncpatton** [comment]
I suspect the main issue is the removal of
```cmake
        if (DEFINED PYTHON_VERSION_STRING)
            set(Python_ADDITIONAL_VERSIONS "${PYTHON_VERSION_STRING}")
        endif()
```
The `manylinux` build images contain multiple versions of Python. So when building wheels, `cmake` is going to need a little bit of help knowing which one to build. The build script passes in these options to `cmake`:
```shell
       -DPYTHON_INCLUDE_DIR:PATH=$PYTHON_INCLUDE_DIR \
       -DPYTHON_LIBRARY:PATH=$PYTHON_LIBRARY \
```
which it gets from... `distutils` 😞 
```shell
PYTHON_BASE_DIR=/opt/python/$PYTHON_TAG-$FULL_PYTHON_VERSION_TAG
export PATH=$PYTHON_BASE_DIR/bin:$PATH
...
export PYTHON_INCLUDE_DIR=$(python -c "from distutils.sysconfig import get_python_inc; print(get_python_inc())")
export PYTHON_LIBRARY=$(python -c "import distutils.sysconfig as sysconfig; print(sysconfig.get_config_var('LIBDIR'))")
```

**Comment by jasoncpatton** [comment]
> ```shell
>        -DPYTHON_INCLUDE_DIR:PATH=$PYTHON_INCLUDE_DIR \
>        -DPYTHON_LIBRARY:PATH=$PYTHON_LIBRARY \
> ```

Though _if_ `cmake` gets pointed to the correct Python interpreter, these probably aren't necessary anymore. I'll need to do some digging to see why it's not picking up on (for example) Python 3.8 from the `$PATH`.

**Comment by GregThain** [comment]
The problem is that the old code in condor's cmake to find cmake variables to build wheels used the cmake modules `FindPythonInterp` and `FindPythonLibs`.  These two are now marked deprecated.  Their replacement, `FindPython3`, as far as I can tell, cannot be used to find the python include directory if the libraries are not installed, as is the case in the manylinux container.

My suggestion then, is do have the wheel build script set -DPYTHON_INCLUDE_DIRS and -DPYTHON_MODULE_SUFFIX on the cmake command line, and protect the place in CondorConfigure.cmake where we call `FindPython3` with if NOT WANT_PYTHON_WHEELS.

**Comment by jasoncpatton** [comment]
Doing some more experimentation, this set of hints:
```
-DPython_ROOT_DIR=/opt/python/cp38-cp38
-DPython3_FIND_STRATEGY=LOCATION
-DPython3_INCLUDE_DIR=/opt/python/cp38-cp38/include/python3.8
```
reduces the error to:
```
-- Could NOT find Python3 (missing: Python3_LIBRARIES Development Development.Embed) (found version "3.8.13")
```

I suspect that removing `Development` from the necessary components for wheel builds will fix this:
```
find_package (Python3 COMPONENTS Interpreter)
```

**Review by timtheisen — APPROVED** [review]
I built the wheels with these updates. It worked well.

**Pull request merged**
