### PR TITLE
/usr/share/condor/config.d directory

### PR DESCRIPTION
**Pull request by matyasselmeci**
This a WIP PR is for [HTCONDOR-45: Add config.d directory for packagers](https://opensciencegrid.atlassian.net/browse/HTCONDOR-45); the idea is we create a second /usr/share/condor/config.d directory where packagers of downstream software (such as GlideinWMS) place their default configs that users aren't supposed to edit. This directory is parsed first so users can override stuff by using /etc.

### CODE REVIEW

**Comment by matyasselmeci** [comment]
This is WIP: I made the changes to the config and RPM packaging but I didn't touch the Debian packaging nor have I tested it.

**Comment by timtheisen** [comment]
This FTBFS. So, closing this and having @matyasselmeci review my changes.

**Comment by matyasselmeci** [comment]
Which changes? Where?

**Comment by timtheisen** [comment]
Two commits associated with https://opensciencegrid.atlassian.net/browse/HTCONDOR-45. The first one is yours, the second one is mine.

**Comment by matyasselmeci** [comment]
OK, found it. Could you make a PR or put the commit in a ticket comment next time? It's kinda buried in the commits list.

**Pull request closed without merging**
