### PR TITLE
docker-api: Added custom Network type

### PR DESCRIPTION
**Pull request by shamoya**
This allows users to specify custom docker networks, other than host or none.
The administrator is responsible for creating those networks in executing machines.
In case of the network does not exist, the job will be held for the correct reason.

This is initial PR, and if additional items are needed we can add them.
P.S we couldn't open the Jira ticket as described below, access to this project in Jira was denied.

# HTCondor Pull Request Checklist for internal reviewers

- [ ] Verify that (GitHub thinks) the merge is clean. If it isn't, and you're confident you can resolve the conflicts, do so. Otherwise, send it back to the original developer.
- [ ] Verify that the related Jira ticket exists and has a target version number and that it is correct.
- [ ] Verify that the Jira ticket is in review status and is assigned to the reviewer.
- [ ] Verify that the Jira ticket (HTCONDOR-xxx) is mentioned at the beginning of the title. Edit it, if not
- [ ] Verify that the branch destination of the PR matches the target version of the ticket
- [ ] Check for correctness of change
- [ ] Check for regression test(s) of new features and bugfixes (if the feature doesn't require root)
- [ ] Check for documentation, if needed
- [ ] Check for version history, if needed
- [ ] Check BaTLab dashboard for successful build (https://batlab.chtc.wisc.edu/results/workspace.php) and test for either the PR or a workspace build by the developer that has the Jira ticket as a comment.
- [ ] Check that commit message references the Jira ticket (HTCONDOR-xxx)

## After the above
- Hit the merge button if the pull request is approved and it is not a security patch (security changes require 2 additional reviews)
- If the pull request is approved, take the ticket out of review state
- Assign JIRA Ticket back to the developer

### CODE REVIEW

**Comment by GregThain** [comment]
Hi Ido -- Thanks for the PR.  I'm curious what network type you'd like to run inside the docker universe container.  Generally speaking, HTCondor pools are heterogeneous environments, so we can't assume at job submit time that any particular worker node has any particular capability.  So, I'd like to amend this PR so that the startd can advertise what kinds of docker networks it can support, so that jobs can match on machines they can run on.  Would that work for your needs?

**Comment by shamoya** [comment]
Thank you @GregThain 
Adding @duduhandelman

We are looking to restrict some users of a specific group to specific parts of the network available to the pool.
For this, we are creating a bridge docker network and adding IPTABLES rules to the docker network chain.
For those users, we have already restricted the use of docker_network_type=host with schedd requirements.

Expanding this PR to the regular schedd/startd ATTRs and match-making capabilities is of course amazing.
We wanted to start with the least intrusive patch possible.
If you want to take it from here we would be delighted (:
we can also continue this PR ourselves if desired.

Thanks again

**Comment by GregThain** [comment]
Hi Ido:

Tell me what you think about PR #475, and if that's sufficient, can we close this PR, and use that one?

**Comment by shamoya** [comment]
Thanks a lot @GregThain, #475 looks great and it's just what we need.
Closing this PR, tell me if we can help in any way.

**Comment by GregThain** [comment]
On 3/1/22 02:25, Ido Shamay wrote:
>
> Thanks a lot @GregThain <https://github.com/GregThain>, #475 
> <https://github.com/htcondor/htcondor/pull/475> looks great and it's 
> just what we need.
> Closing this PR, tell me if we can help in any way.
>

It might be some weeks before this pr gets into a released version of 
HTCondor.  You seem saavy enough to build HTCondor from scratch -- feel 
free to build your own HTCondor with this PR, and let me know if it does 
what you need.

-greg

**Comment by shamoya** [comment]
No worries, we already have a patched (this PR version) HTCondor on top of V9_0-branch running in our pool.
I'll check the new patch of the new PR and let you know if it's all working well.

**Pull request closed without merging**
