### PR TITLE
(HTCONDOR-2579)  Re-`locate()` the collector on a lost connection.

### PR DESCRIPTION
**Pull request by Todd-L-Miller**
In `DCCollector::sendTCPUpdate()`, if an update fails, the socket is destroyed and the connection immediately rebuilt; this PR forces the address of the collector to be resolved again when this happens.

Also resolve the collector's address again if the update failed for some reason that did not result in the destruction of the socket (e.g., the socket wasn't created because the connection failed).  This will result in an additional look-ups, but I don't think there's anything we can do about that.

# HTCondor Pull Request Checklist for internal reviewers

- [ ] Verify that (GitHub thinks) the merge is clean. If it isn't, and you're confident you can resolve the conflicts, do so. Otherwise, send it back to the original developer.
- [ ] Verify that the related Jira ticket exists and has a target version number and that it is correct.
- [ ] Verify that the Jira ticket is in review status and is assigned to the reviewer.
- [ ] Verify that the Jira ticket (HTCONDOR-xxx) is mentioned at the beginning of the title. Edit it, if not
- [ ] Verify that the branch destination of the PR matches the target version of the ticket
- [ ] Check for correctness of change
- [ ] Check for regression test(s) of new features and bugfixes (if the feature doesn't require root)
- [ ] Check for documentation, if needed  (documentation [build logs](https://readthedocs.org/projects/htcondor/builds/))
- [ ] Check for version history, if needed
- [ ] Check BaTLab dashboard for successful build (https://batlab.chtc.wisc.edu/results/workspace.php) and test for either the PR or a workspace build by the developer that has the Jira ticket as a comment.
- [ ] Check that each commit message references the Jira ticket (HTCONDOR-xxx)

## After the above
- Hit the merge button if the pull request is approved and it is not a security patch (security changes require 2 additional reviews)
- If the pull request is approved, take the ticket out of review state
- Assign JIRA Ticket back to the developer

### CODE REVIEW

**Comment by Todd-L-Miller** [comment]
I'm not seeing a plausible way to test this at the moment, without root.

**Review by JaimeFrey — COMMENTED** [review]
deepCopy() would be more properly named deepishCopy(). But I think its current behavior works for what we need here. A truly deep copy would surely rouse a Balrog.

**Review by JaimeFrey — APPROVED** [review]
I'm not happy with what this code does (make a new DCCollector object and use it to mostly-overwrite the existing DCCollector object), but it looks like it does what we need and is much simpler than the refactoring necessary for a "good" implementation.

**Comment by Todd-L-Miller** [comment]
> I'm not happy with what this code does (make a new DCCollector object and use it to mostly-overwrite the existing DCCollector object), but it looks like it does what we need and is much simpler than the refactoring necessary for a "good" implementation.

I 100% concur with this evaluation.

**Pull request merged**
