### PR TITLE
V9_3_2-HTCONDOR-820-branch

### PR DESCRIPTION
**Pull request by Todd-L-Miller**
Implement `allowed_execute_duration`, which is like `allowed_job_duration` but doesn't count transfer time.

# HTCondor Pull Request Checklist for internal reviewers

- [x] Verify that (GitHub thinks) the merge is clean. If it isn't, and you're confident you can resolve the conflicts, do so. Otherwise, send it back to the original developer.
- [x] Verify that the related Jira ticket exists and has a target version number and that it is correct.
- [x] Verify that the Jira ticket is in review status and is assigned to the reviewer.
- [x] Verify that the Jira ticket (HTCONDOR-xxx) is mentioned at the beginning of the title. Edit it, if not
- [x] Verify that the branch destination of the PR matches the target version of the ticket
- [x] Check for correctness of change
- [x] Check for documentation, if needed
- [x] Check for version history, if needed
- [x] Check BaTLab dashboard for successful build (https://batlab.chtc.wisc.edu/results/workspace.php) and test for either the PR or a workspace build by the developer that has the Jira ticket as a comment.
- [x] Check that commit message references the Jira ticket (HTCONDOR-xxx)

## After the above
- Hit the merge button if the pull request is approved and it is not a security patch (security changes require 2 additional reviews)
- If the pull request is approved, take the ticket out of review state
- Assign JIRA Ticket back to the developer

### CODE REVIEW

**Review by JaimeFrey — CHANGES_REQUESTED** [review]
This code looks good. Needs a version history entry.
I just realized that both ATTR_JOB_ALLOWED_JOB_DURATION and ATTR_JOB_ALLOWED_EXECUTE_DURATION should to be deleted from submit_ad in CondorJob::buildSubmitAd() in src/condor_gridmanager/condorjob.cpp (where we delete all job policy attributes).

**Comment by Todd-L-Miller** [comment]
I believe c2f44e6 and 38fd180 address your concerns, although I don't know how to test the latter.

**Comment by JaimeFrey** [comment]
No need to test the Condor-C change.

**Review by JaimeFrey — APPROVED** [review]
Looks good now.

**Comment by Todd-L-Miller** [comment]
The dashboard proper isn't working right now, but https://batlab.chtc.wisc.edu/test-results/run-details.php?runid=563634 shows the run for PR#315 being clean.

**Pull request merged**
