### PR TITLE
HTCONDOR-1146 Compute proper python interpreter path for condor_watch_q

### PR DESCRIPTION
**Pull request by GregThain**
We hope this makes life easier for conda, pip and other python packagers

<Insert PR description here, and leave checklist below for code review.>

# HTCondor Pull Request Checklist for internal reviewers

- [ ] Verify that (GitHub thinks) the merge is clean. If it isn't, and you're confident you can resolve the conflicts, do so. Otherwise, send it back to the original developer.
- [ ] Verify that the related Jira ticket exists and has a target version number and that it is correct.
- [ ] Verify that the Jira ticket is in review status and is assigned to the reviewer.
- [ ] Verify that the Jira ticket (HTCONDOR-xxx) is mentioned at the beginning of the title. Edit it, if not
- [ ] Verify that the branch destination of the PR matches the target version of the ticket
- [ ] Check for correctness of change
- [ ] Check for regression test(s) of new features and bugfixes (if the feature doesn't require root)
- [ ] Check for documentation, if needed  (documentation [build logs](https://readthedocs.org/projects/htcondor/builds/))
- [ ] Check for version history, if needed
- [ ] Check BaTLab dashboard for successful build (https://batlab.chtc.wisc.edu/results/workspace.php) and test for either the PR or a workspace build by the developer that has the Jira ticket as a comment.
- [ ] Check that each commit message references the Jira ticket (HTCONDOR-xxx)

## After the above
- Hit the merge button if the pull request is approved and it is not a security patch (security changes require 2 additional reviews)
- If the pull request is approved, take the ticket out of review state
- Assign JIRA Ticket back to the developer

### CODE REVIEW

**Comment by timtheisen** [comment]
@JaimeFrey On MacOS, this changes the shebang from `#!/usr/bin/python3` to `#!/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/bin/python3.9`
Is that acceptable?

**Comment by timtheisen** [comment]
@johnkn This changes the shebang from `#!/usr/bin/python3` to '#!'
Is this acceptable?

**Comment by GregThain** [comment]
> @JaimeFrey On MacOS, this changes the shebang from `#!/usr/bin/python3` to `#!/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/bin/python3.9` Is that acceptable?

Or, does this mean that we are finding the wrong python on mac, and should pass additional magic flags to cmake to encourage it to use /usr/bin/python3 ?

**Comment by timtheisen** [comment]
@GregThain All the Linux tarballs look fine. Some unanswered questions with Windows and Mac.

**Comment by JaimeFrey** [comment]
On macOS, Python3 isn't included in the base OS. Instead, it's included in the developer tools, which can be installed in one or more locations. /usr/bin/python3 is a stub that redirects to the python3 binary in the active developer installation (which can be selected by the user by running xcode-select). The location used on our build machines will not be valid on all users' machines. As such, we should keep /usr/bin/python3 on the shebang line for macOS.

**Comment by GregThain** [comment]
Push a fix for mac...

**Review by timtheisen — APPROVED** [review]
Good enough

**Pull request merged**
