### PR TITLE
HTCONDOR-1340 kill boinc grid-type

### PR DESCRIPTION
**Pull request by JaimeFrey**
https://opensciencegrid.atlassian.net/browse/HTCONDOR-1340

# HTCondor Pull Request Checklist for internal reviewers

- [ ] Verify that (GitHub thinks) the merge is clean. If it isn't, and you're confident you can resolve the conflicts, do so. Otherwise, send it back to the original developer.
- [ ] Verify that the related Jira ticket exists and has a target version number and that it is correct.
- [ ] Verify that the Jira ticket is in review status and is assigned to the reviewer.
- [ ] Verify that the Jira ticket (HTCONDOR-xxx) is mentioned at the beginning of the title. Edit it, if not
- [ ] Verify that the branch destination of the PR matches the target version of the ticket
- [ ] Check for correctness of change
- [ ] Check for regression test(s) of new features and bugfixes (if the feature doesn't require root)
- [ ] Check for documentation, if needed
- [ ] Check for version history, if needed
- [ ] Check BaTLab dashboard for successful build (https://batlab.chtc.wisc.edu/results/workspace.php) and test for either the PR or a workspace build by the developer that has the Jira ticket as a comment.
- [ ] Check that each commit message references the Jira ticket (HTCONDOR-xxx)

## After the above
- Hit the merge button if the pull request is approved and it is not a security patch (security changes require 2 additional reviews)
- If the pull request is approved, take the ticket out of review state
- Assign JIRA Ticket back to the developer

### CODE REVIEW

**Comment by JaimeFrey** [comment]
Ah. I was targeting just the boinc grid universe code. But I see know that Greg made HAVE_BOINC control both that and the startd backfill boinc code in 9.10.0. I also realize now that the boinc_gahp has been absent from the tarball release ever since we based it off of the native packages. I don't think this PR needs to include removing the startd code. That can be part of a code cleanup ticket in the 10.X series.

**Comment by JaimeFrey** [comment]
Question for this ticket and HTCONDOR-1235: How much of the feature removal should be called out in the release notes?

**Comment by timtheisen** [comment]
I don't think that we should mention boinc removal, only because it has been absent for some time. We would have to review each of the features and decide whether to mention its removal.

**Review by timtheisen — CHANGES_REQUESTED** [review]
I think that we need to scrub boinc from the manual as well.

**Comment by JaimeFrey** [comment]
With HAVE_BOINC disabled or removed, the whole startd backfill system is not usable. It has ambitions to support other backfilling applications, but only BOINC is supported. Do we scrub all of the ENABLE_BACKFILL text in the manual as well?

**Comment by timtheisen** [comment]
Let's mention this at the Monday meeting.

**Comment by JaimeFrey** [comment]
Canceling this PR. Will make a new one with other changes.

**Pull request closed without merging**
