### PR TITLE
HTCONDOR-836 Add option to not build daemons

### PR DESCRIPTION
**Pull request by GregThain**
as requested by our client-only packagers

<Insert PR description here, and leave checklist below for code review.>

# HTCondor Pull Request Checklist for internal reviewers

- [ ] Verify that (GitHub thinks) the merge is clean. If it isn't, and you're confident you can resolve the conflicts, do so. Otherwise, send it back to the original developer.
- [ ] Verify that the related Jira ticket exists and has a target version number and that it is correct.
- [ ] Verify that the Jira ticket is in review status and is assigned to the reviewer.
- [ ] Verify that the Jira ticket (HTCONDOR-xxx) is mentioned at the beginning of the title. Edit it, if not
- [ ] Verify that the branch destination of the PR matches the target version of the ticket
- [ ] Check for correctness of change
- [ ] Check for regression test(s) of new features and bugfixes (if the feature doesn't require root)
- [ ] Check for documentation, if needed  (documentation [build logs](https://readthedocs.org/projects/htcondor/builds/))
- [ ] Check for version history, if needed
- [ ] Check BaTLab dashboard for successful build (https://batlab.chtc.wisc.edu/results/workspace.php) and test for either the PR or a workspace build by the developer that has the Jira ticket as a comment.
- [ ] Check that each commit message references the Jira ticket (HTCONDOR-xxx)

## After the above
- Hit the merge button if the pull request is approved and it is not a security patch (security changes require 2 additional reviews)
- If the pull request is approved, take the ticket out of review state
- Assign JIRA Ticket back to the developer

### CODE REVIEW

**Review by timtheisen — APPROVED** [review]
LGTM

**Comment by duncanmmacleod** [comment]
Unfortunately, this doesn't work:

```text
CMake Error at build/cmake/macros/AppendVar.cmake:54 (get_property):
  get_property could not find TARGET condor_collector.  Perhaps it has not
  yet been created.
Call Stack (most recent call first):
  build/cmake/macros/CondorDaemon.cmake:44 (append_target_property_flag)
  src/condor_collector.V6/CMakeLists.txt:37 (condor_daemon)
```

The issue, I think, is that the `if (cxx_full_relro_and_pie)` conditional is _outside_ of the `if (BUILD_DAEMONS)` conditional, so the target isn't defined:

https://github.com/htcondor/htcondor/blob/2b66c1debd89d2a25ec9a919c48691d92c9e7cbf/build/cmake/macros/CondorDaemon.cmake#L36-L48

**Comment by GregThain** [comment]
What is your cmake command line?

**Comment by duncanmmacleod** [comment]
> What is your cmake command line?

https://github.com/conda-forge/htcondor-feedstock/blob/c8ce22507c29ed3a77b5114e4b6055fb8388e647/recipe/build.sh

**Comment by GregThain** [comment]
Ah, I see -- it's the `PROPER=true` that brings in relro.  I'm pretty sure your patch will fix this problem.

**Pull request merged**
