### PR TITLE
HTCONDOR-2196 Robustify checkpoint tests

### PR DESCRIPTION
**Pull request by GregThain**
The Checkpoint tests look for the job's output files immediately after the userlog says the job is done, but sometimes file transfer hasn't finished yet.  Let's poll a couple of times to be sure the files are there.

<Insert PR description here, and leave checklist below for code review.>

# HTCondor Pull Request Checklist for internal reviewers

- [x] Verify that (GitHub thinks) the merge is clean. If it isn't, and you're confident you can resolve the conflicts, do so. Otherwise, send it back to the original developer.
- [x] Verify that the related Jira ticket exists and has a target version number and that it is correct.
- [x] Verify that the Jira ticket is in review status and is assigned to the reviewer.
- [x] Verify that the Jira ticket (HTCONDOR-xxx) is mentioned at the beginning of the title. Edit it, if not
- [x] Verify that the branch destination of the PR matches the target version of the ticket
- [x] Check for correctness of change
- [x] Check for regression test(s) of new features and bugfixes (if the feature doesn't require root)
- [x] Check for documentation, if needed  (documentation [build logs](https://readthedocs.org/projects/htcondor/builds/))
- [x] Check for version history, if needed
- [x] Check BaTLab dashboard for successful build (https://batlab.chtc.wisc.edu/results/workspace.php) and test for either the PR or a workspace build by the developer that has the Jira ticket as a comment.
- [x] Check that each commit message references the Jira ticket (HTCONDOR-xxx)

## After the above
- Hit the merge button if the pull request is approved and it is not a security patch (security changes require 2 additional reviews)
- If the pull request is approved, take the ticket out of review state
- Assign JIRA Ticket back to the developer

### CODE REVIEW

**Comment by bbockelm** [comment]
Logging that the file transfer is complete while the file transfer is _not_ complete sounds like a bug, no?  Are we working around a real issue here?

**Comment by Todd-L-Miller** [comment]
Looks like the real issue is that it's possible for `the_completed_job()` to return if a job times out instead of completing.

**Comment by GregThain** [comment]
Changes to fix underlying problems, as suggested by @Todd-L-Miller

**Review by Todd-L-Miller — APPROVED** [review]
LGTM.

**Review by ColeBollig — APPROVED** [review]
Likewise... LGTM

**Pull request merged**
