### PR TITLE
HTCONDOR-1693: Remove TOFU openssl 3 deprecation warnings

### PR DESCRIPTION
**Pull request by ColeBollig**
<Insert PR description here, and leave checklist below for code review.>

# HTCondor Pull Request Checklist for internal reviewers

- [ ] Verify that (GitHub thinks) the merge is clean. If it isn't, and you're confident you can resolve the conflicts, do so. Otherwise, send it back to the original developer.
- [ ] Verify that the related Jira ticket exists and has a target version number and that it is correct.
- [ ] Verify that the Jira ticket is in review status and is assigned to the reviewer.
- [ ] Verify that the Jira ticket (HTCONDOR-xxx) is mentioned at the beginning of the title. Edit it, if not
- [ ] Verify that the branch destination of the PR matches the target version of the ticket
- [ ] Check for correctness of change
- [ ] Check for regression test(s) of new features and bugfixes (if the feature doesn't require root)
- [ ] Check for documentation, if needed
- [ ] Check for version history, if needed
- [ ] Check BaTLab dashboard for successful build (https://batlab.chtc.wisc.edu/results/workspace.php) and test for either the PR or a workspace build by the developer that has the Jira ticket as a comment.
- [ ] Check that each commit message references the Jira ticket (HTCONDOR-xxx)

## After the above
- Hit the merge button if the pull request is approved and it is not a security patch (security changes require 2 additional reviews)
- If the pull request is approved, take the ticket out of review state
- Assign JIRA Ticket back to the developer

### CODE REVIEW

**Comment by ColeBollig** [comment]
If my diving into the openssl docs don't deceive me then I believe the openssl 3 line does the equivalent of the original setting of the asn1_flag for the EC_KEY. Also, note I was unsure how to test this manually.
Tagging @bbockelm because this was his code originally.

**Comment by bbockelm** [comment]
Easiest way to tell if you're doing it right is to print out the generated certificate and see if a named curve is being used in the signature or if it just lists the point on the curve.  Example:
```
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            ca:35:93:7a:66:e3:2d:78
    Signature Algorithm: ecdsa-with-SHA256
        Issuer: O=condor, CN=example.com
        Validity
            Not Before: Dec  3 14:11:18 2022 GMT
            Not After : Nov 30 14:11:17 2032 GMT
        Subject: O=condor, CN=hcc-briantest7.unl.edu
        Subject Public Key Info:
            Public Key Algorithm: id-ecPublicKey
                Public-Key: (256 bit)
                pub: 
                    04:eb:0f:ba:52:d1:de:f7:d2:7d:dd:d3:53:87:11:
                    13:88:50:17:c4:85:29:b6:1e:4a:bd:64:ad:70:83:
                    12:7f:21:e6:1c:80:d8:8a:56:14:29:3c:21:51:6b:
                    dc:b8:75:0e:93:99:ae:06:6f:f0:d7:cd:56:d8:0a:
                    87:94:ca:38:d4
                ASN1 OID: prime256v1
                NIST CURVE: P-256
        X509v3 extensions:
            X509v3 Subject Key Identifier: 
                A6:2F:DD:09:C3:03:99:D5:6D:4D:CE:82:F9:E5:96:A1:33:DB:23:DF
            X509v3 Authority Key Identifier: 
                keyid:A6:2F:DD:09:C3:03:99:D5:6D:4D:CE:82:F9:E5:96:A1:33:DB:23:DF

            X509v3 Basic Constraints: critical
                CA:TRUE
            X509v3 Key Usage: critical
                Certificate Sign
    Signature Algorithm: ecdsa-with-SHA256
         30:46:02:21:00:af:9c:c3:18:e2:24:33:91:a9:bb:d5:a7:98:
         41:de:cc:42:e1:33:30:2c:89:9a:32:fd:7b:55:6d:bb:c2:2d:
         59:02:21:00:b6:2d:5e:4d:9d:18:53:22:91:76:24:8d:78:12:
         0b:e4:e9:08:09:6f:87:4e:70:4b:b4:b5:e0:9d:01:b0:dc:eb
```

**Comment by ColeBollig** [comment]
Thanks for the how to Brian. I will switch this to a draft and then verify this change

**Comment by JaimeFrey** [comment]
According to the OpenSSL documentation (https://www.openssl.org/docs/man3.0/man3/EC_GROUP_copy.html), the named_curve setting is the default in OpenSSL 1.1.0 and above (vs explicit_curve being the default prior). Thus, we probably don't need either call with newer OpenSSL versions.

**Comment by bbockelm** [comment]
> Thus, we probably don't need either call with newer OpenSSL versions.

Good catch!  I forgot how _old_ the RHEL7 OpenSSL is...

@ColeBollig if you can verify the generated certs look correct on RHEL7 / 8 / 9, I'm OK with dropping the explicit setting.

**Comment by JaimeFrey** [comment]
I can confirm that rhel7 needs the named_curve call and rhel9 does not.

**Review by JaimeFrey — APPROVED** [review]
LGTM

**Pull request merged**
