### PR TITLE
HTCONDOR-2589 new-security-config

### PR DESCRIPTION
**Pull request by JaimeFrey**
Define new meta-knob security:recommended, to replace security:recommended_v9_0. Main differences are updating special security principals (remove condor_pool@) and making authentication optional for READ (keeping integrity/encryption).

Also, all installation methods now use security:recommended as their base. get_htcondor continues to add the ANONYMOUS auth method just for backwards-compatibility with older versions.

<Insert PR description here, and leave checklist below for code review.>

# HTCondor Pull Request Checklist for internal reviewers

- [x] Verify that (GitHub thinks) the merge is clean. If it isn't, and you're confident you can resolve the conflicts, do so. Otherwise, send it back to the original developer.
- [x] Verify that the related Jira ticket exists and has a target version number and that it is correct.
- [x] Verify that the Jira ticket is in review status and is assigned to the reviewer.
- [x] Verify that the Jira ticket (HTCONDOR-xxx) is mentioned at the beginning of the title. Edit it, if not
- [x] Verify that the branch destination of the PR matches the target version of the ticket
- [x] Check for correctness of change
- [x] Check for regression test(s) of new features and bugfixes (if the feature doesn't require root)
- [ ] Check for documentation, if needed  (documentation [build logs](https://readthedocs.org/projects/htcondor/builds/))
- [ ] Check for version history, if needed
- [x] Check BaTLab dashboard for successful build (https://batlab.chtc.wisc.edu/results/workspace.php) and test for either the PR or a workspace build by the developer that has the Jira ticket as a comment.
- [x] Check that each commit message references the Jira ticket (HTCONDOR-xxx)

## After the above
- Hit the merge button if the pull request is approved and it is not a security patch (security changes require 2 additional reviews)
- If the pull request is approved, take the ticket out of review state
- Assign JIRA Ticket back to the developer

### CODE REVIEW

**Comment by JaimeFrey** [comment]
We still need linux packaging code to remove the old 00-htcondor-9.0.config config file.

**Comment by timtheisen** [comment]
Do we need to do anything with:

- src/condor_examples/50-security
- src/condor_examples/00-minicondor
- build/docker/services/mini/00-minicondor-ubuntu

**Review by timtheisen — APPROVED** [review]
What's here is good.

I'm a little concerned that 00-security is not listed in the condor_examples CMakeLists.txt and 50-security is.

**Comment by JaimeFrey** [comment]
00-security is listed in src/condor_examples/CMakleLists.txt. I just noticed that 00-minicondor will be read before 00-security if they're both present. I think we want 00-security to go first, and have 00-minicondor tweak the default configuration. If 00-minicondor appears without 00-security, then it should use the security:recommended meta-knob.

**Comment by JaimeFrey** [comment]
It looks like 50-security isn't referenced anywhere. It should probably be removed.

**Comment by timtheisen** [comment]
I suppose 000-security would sort before 00-minicondor. The alteranative is putting the security configuration in boiler plate configuration.

**Comment by JaimeFrey** [comment]
00-minicondor sorts before 000-security. '-' comes before '0' in ASCII. I think we can just remove the security settings in 00-minicondor and use those in security:recommended.

**Comment by timtheisen** [comment]
I agree about removing the security setting from the minicondor.

**Comment by timtheisen** [comment]
I made the changes that we discussed this morning.
What about the mini-condor network configuration. We bound to the loopback interface because the existing security was wake. Can we remove this now that the default security should be fine?

**Comment by timtheisen** [comment]
@JaimeFrey I think this is ready to merge.

**Pull request merged**
